--- #YAML:1.0
name:                Acme-Echo
version:             0.02
abstract:            Display perl statements before, after, and/or during execution
license:             unknown
generated_by:        ExtUtils::MakeMaker version 6.30_01
author:              David Westbrook <dwestbrook@gmail.com>
distribution_type:   module
requires:     
    Filter::Simple:                0.82
    IO::Scalar:                    0
    PPI:                           1.11
    Test::More:                    0
meta-spec:
    url: <http://module-build.sourceforge.net/META-spec-new.html>;
    version: 1.1
